// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syslhpcowxicoueuysni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5c2xocGNvd3hpY291ZXV5c25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDQ4ODMsImV4cCI6MjA1OTQyMDg4M30.s6PnyOT04pbOJpjhEJdER_MzcsF2P2nUvL2suaeaBV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);